### ISSUE TITLE
cardinality of questionnaire.item.code 0..1 instead of 0..*

### ISSUE THREAD

**Issue by Rosnyni** [lhncbc/formbuilder-lhcforms#66]
fhir R4 mention a 0..* cardinality for questionnaire.item.code and the current version of lhcform only allow for one code per item.

**Comment by plynchnlm** [comment]
Yes.  Early in our design phase the decision was made to simplify the UI by only allowing the entry of one code.  I suppose, if you only need to enter one code, it does make it a bit simpler.  That design decision has since been overturned, and allowing more than one code is on our list of things to do,  but we haven't gotten to it yet.  It would help us to prioritize that if you could let us know whether you are reporting this just because you noticed the problem, or because it is limiting what you actually want to do.

**Comment by Rosnyni** [comment]
I notice this because I was thinking of using this attribute to store both a local code and a standardised one. 

I have some other option to resolve my issue, but having multiple code is probably the easiest and the most gracious.

**Comment by plynchnlm** [comment]
This is now fixed.

**Comment by Rosnyni** [comment]
Thank you
